<?php
/**
 * Created by PhpStorm.
 * User: New York
 * Date: 10/8/2018
 * Time: 0:24 AM
 */

namespace app\components;


use yii\web\Controller;

class BaseController extends Controller
{
    public function beforeAction($action)
    {
        if (\Yii::$app->getRequest()->getCookies()->has('lang')) {
            \Yii::$app->language = \Yii::$app->getRequest()->getCookies()->getValue('lang');
        } else {
            \Yii::$app->language = 'en';
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}