<?php
/**
 * Created by PhpStorm.
 * User: Cuong
 * Date: 8/9/2018
 * Time: 5:13 PM
 */

namespace app\components;

use yii\web\Cookie;

class BaseController extends \yii\web\Controller
{
    public function beforeAction($action)
    {
        if (\Yii::$app->getRequest()->getCookies()->has('lang')) {
            \Yii::$app->language = \Yii::$app->getRequest()->getCookies()->getValue('lang');
        } else {
            \Yii::$app->language = 'en';
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}