<?php
/**
 * Created by PhpStorm.
 * User: Cuong
 * Date: 8/15/2018
 * Time: 4:14 PM
 */

namespace app\components;

use yii\jui\Widget;

class StamfordBridge extends Widget
{
    public $model;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
      return $this->render('Chelsea', ['product' => $this->model]);
      //
    }
}

